# SOPS configuration for AWS KMS encryption
# Uses the same KMS key as kstlib (eu-west-3)
creation_rules:
  - path_regex: .*\.(yml|yaml|json)$
    encrypted_regex: .*(?:key|password|secret|token|credentials?|private).*
    kms: arn:aws:kms:eu-west-3:770922560222:key/ce47630f-5d5a-4be0-9457-408a4983d4dd
