# SOPS Configuration Example
# ===========================
#
# Copy this file to .sops.yaml (remove .example) in one of these locations:
#   - Current directory        (applies to this folder only)
#   - ~/.sops.yaml             (global, macOS/Linux)
#   - %APPDATA%\sops\.sops.yaml (global, Windows)
#
# Then replace the placeholder public key with your own:
#   Windows:     age-keygen -y "$env:APPDATA\sops\age\keys.txt"
#   macOS/Linux: age-keygen -y ~/.config/sops/age/keys.txt
#
# For full documentation: https://github.com/getsops/sops

creation_rules:
  # Default rule: match any YAML file
  # SOPS matches on the INPUT file path
  - path_regex: .*\.(yml|yaml)$
    # Only encrypt keys containing sensitive keywords (keeps structure readable)
    encrypted_regex: .*(?:sops|key|password|secret|token|credentials?).*
    # Example key (from age-key.example.txt) - FOR TESTING ONLY
    # Replace with YOUR age public key for real use
    age: age1zsnz8l28tjg9gcxe3rgt5pycvuzwvwnjz55840875v2aagwgsg5s7sgpp9

# encrypted_regex explanation
# ---------------------------
# Without encrypted_regex: ALL values are encrypted (hard to read structure)
# With encrypted_regex: only matching keys are encrypted
#
# Example with encrypted_regex: '^.*(password|secret).*$'
#
#   mail:
#     smtp:
#       host: smtp.gmail.com          # NOT encrypted (readable)
#       port: 587                     # NOT encrypted (readable)
#       username: alice@example.com   # NOT encrypted (readable)
#       password: ENC[AES256_GCM...]  # ENCRYPTED (contains "password")
#
# This makes the file structure visible while protecting sensitive values.

# Path-specific rules (optional)
# ------------------------------
# You can have different keys for different paths:
#
# creation_rules:
#   - path_regex: \.prod\.(yml|yaml)$
#     encrypted_regex: '^.*(password|secret|token|key|credentials?).*$'
#     age: age1prod_key_here
#
#   - path_regex: \.dev\.(yml|yaml)$
#     encrypted_regex: '^.*(password|secret|token|key|credentials?).*$'
#     age: age1dev_key_here
#
#   # Fallback for everything else
#   - path_regex: .*\.(yml|yaml)$
#     encrypted_regex: '^.*(password|secret|token|key|credentials?).*$'
#     age: age1default_key_here

# Multiple recipients (team setup)
# --------------------------------
# When multiple people need access, list all their public keys:
#
# creation_rules:
#   - path_regex: .*\.(yml|yaml)$
#     encrypted_regex: '^.*(password|secret|token|key|credentials?).*$'
#     age: >-
#       age1alice_public_key,
#       age1bob_public_key,
#       age1charlie_public_key

# AWS KMS (cloud setup)
# ---------------------
# For production environments, use AWS KMS instead of age:
#
# creation_rules:
#   - path_regex: .*\.prod\.(yml|yaml)$
#     encrypted_regex: '^.*(password|secret|token|key|credentials?).*$'
#     kms: arn:aws:kms:us-east-1:123456789:key/your-key-id
